#!/bin/bash
# Disable and remove the AirPods extension.
source "$(dirname "$(readlink -f "$0")")/../../lib/common.sh"

UUID=airpods@finni

step "Disabling extension"
gnome_ext_set_enabled "$UUID" false

step "Removing files"
rm -rf "$HOME/.local/share/gnome-shell/extensions/$UUID"

step "Done"
info "The AirPods still work as ordinary Bluetooth headphones."
